### ISSUE TITLE
Organize app with new layout

### ISSUE THREAD

**Issue by LigoMan99** [Ligo-Ai-Inc/Markup#1]
The app layout should look exactly like this below. I understand some of the menus will not be finished but lets show the layout of what it will look like for the demo:

![image](https://github.com/user-attachments/assets/3dcc38f1-72e0-4431-9a0d-9f0385953485)

Icon for Photo: https://fonts.google.com/icons?icon.set=Material+Symbols&icon.style=Outlinedrl&selected=Material+Symbols+Outlined:add_a_photo:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=photo&icon.size=24&icon.color=%235f6368

Icon for Measure: https://fonts.google.com/icons?icon.set=Material+Symbols&icon.style=Outlinedrl&selected=Material+Symbols+Outlined:full_stacked_bar_chart:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=measure&icon.size=24&icon.color=%235f6368
Please rotate icon 90 degrees

**Comment by LigoMan99** [comment]
> The icon cannot be rotate in streamlit

Download the icon and then rotate the png?

**Comment by NguyenTheAn** [comment]
no, it doesn't allow that, you can only use the icon from the Meterial font, the name of the icon is fixed

**Comment by LigoMan99** [comment]
Ok. Still use that icon. Thanks

**Comment by NguyenTheAn** [comment]
Done
